

GRAPHQL http://localhost:50002/query

query IntrospectionQuery {
    __schema {
    types {
      name
      description
      fields {
        name
        description
      }
    }
  }
}
####
GRAPHQL http://localhost:50002/query

mutation LoginUser($logininput : Login!){
  loginUser(input :$logininput) {
    _id

  }
}
{
  "logininput": {
    "username": "mitch@gmail.com",
    "password": "letmein"
  }
}

####
GRAPHQL http://localhost:50002/graphql
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pdGNoQGdtYWlsLmNvbSIsImV4cCI6MTcwMDI4MzQyNn0.yGJ12K17ZMLck_TmsMRlhXyTqgZRkBTkmUGKfi42JQA

query  Game {
games { name }
}
{}














