version: "3.5"
services:
  arangodb:
    image: arangodb:latest
    container_name: stg-arangodb
    restart: always
    ports:
      - 50001:8529
    environment:
      ARANGO_ROOT_PASSWORD: letmein
    volumes:
      - /home/smacktalk/stg/arangodbstorage:/var/lib/arangodb3
    networks:
      # Networks to join (Services on the same network can communicate with each other using their name)
      - stg
    #command: arangod --server.authentication=false

  backend:
    container_name: stg-backend
    # Configuration for building the docker image for the service
    build:
      context: ./back # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "50002:50002" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    environment:
      GO_ENV: prod

    depends_on:
      - arangodb
    networks:
      # Networks to join (Services on the same network can communicate with each other using their name)
      - stg
    #healthcheck:
    #   test: ["CMD", "curl", "-f", "http://arangodb:8529"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5


  frontend:
    container_name: stg-frontend
    # Configuration for building the docker image for the service
    build:
      context: ./front # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "50003:50003" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    
    environment:
      DEV: "false"

    depends_on:
      - backend
    networks:
      # Networks to join (Services on the same network can communicate with each other using their name)
      - stg

networks:
  stg:
