package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"back/graph/model"
	"context"
	"fmt"
)

// GetStats is the resolver for the GetStats field.
func (r *queryResolver) GetStats(ctx context.Context) ([]*model.Stats, error) {
	panic(fmt.Errorf("not implemented: GetStats - GetStats"))
}
