// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CompletedstatusInput struct {
	ID        string `json:"id"`
	Completed bool   `json:"completed"`
}

type Contest struct {
	Key         string     `json:"_key"`
	ID          string     `json:"_id"`
	Rev         string     `json:"rev"`
	Start       string     `json:"start"`
	Startoffset string     `json:"startoffset"`
	Stop        string     `json:"stop"`
	Stopoffset  string     `json:"stopoffset"`
	Outcomes    []*Outcome `json:"outcomes"`
	Games       []*Game    `json:"games"`
	Venue       *Venue     `json:"venue,omitempty"`
}

type Game struct {
	Key  string `json:"_key"`
	ID   string `json:"_id"`
	Rev  string `json:"rev"`
	Name string `json:"name"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginData struct {
	Token    string    `json:"token"`
	Userdata *UserData `json:"userdata"`
}

type NewTodo struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Outcome struct {
	Key         string   `json:"_key"`
	ID          string   `json:"_id"`
	Rev         string   `json:"rev"`
	Start       string   `json:"start"`
	Startoffset string   `json:"startoffset"`
	Stop        string   `json:"stop"`
	Stopoffset  string   `json:"stopoffset"`
	Results     []*Place `json:"results"`
}

type Place struct {
	Key      string `json:"_key"`
	ID       string `json:"_id"`
	Rev      string `json:"rev"`
	Playerid string `json:"playerid"`
	Place    int    `json:"place"`
	Result   string `json:"result"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type UserData struct {
	Key       string `json:"_key"`
	ID        string `json:"_id"`
	Rev       string `json:"rev"`
	Firstname string `json:"firstname"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type Venue struct {
	Key     string `json:"_key"`
	ID      string `json:"_id"`
	Rev     string `json:"rev"`
	Address string `json:"address"`
	Lat     string `json:"lat"`
	Lng     string `json:"lng"`
}
